# For full config options, check the docs:
#    docs.serverless.com
service: bot-scheduler
app: stockm

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 60
  # stage: dev
  # region: ap-southeast-1
  environment:
    TOKEN: ${env:TOKEN}
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  update_w_job:
    handler: handler.update_users
    events:
      - schedule: cron(0/02 * * ? *)  # Every 02 Minute In Every Day
#      - schedule: cron(16 10 ? * MON-FRI *)  # 10:10am UTC = 01:10pm

  update_users_BH:
    handler: handler.update_users
    events:
      - schedule: cron(16 10 ? * MON-FRI *)  # 10:10am UTC = 01:10pm BH
  
  update_users_US:
    handler: handler.update_users
    events:
      - schedule: cron(00 20 ? * TUE-SAT *)  # 8pm UTC = 4pm US

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
